/**
 * transitGraph.ts
 * ===============
 * Reads the static transit graph snapshots built by
 * `scripts/build_transit_graph.py` (city2graph + OSMnx).
 *
 * Exports:
 *   TRANSIT_GRAPH_NODES  — all stations with lat/lng/system/name
 *   TRANSIT_GRAPH_EDGES  — connections between stations
 *   nearestGraphStations — nearest N stations to a point
 */

import type { RailStation } from "./transitStations";

export type TransitGraphNode = {
  id: string;
  lat: number;
  lng: number;
  nameEn: string;
  nameTh: string;
  system: string;
  color: string;
  line?: string;
  source: string;
  betweenness?: number;
  degree?: number;
};

export type TransitGraphEdge = {
  source: string;
  target: string;
  distanceKm: number;
  system: string;
};

// Lazy-load the JSON snapshots (generated by build_transit_graph.py).
// Falls back to empty arrays if the files don't exist yet.
function loadNodes(): TransitGraphNode[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const raw = require("./transitGraph.nodes.json") as { nodes: TransitGraphNode[] };
    return raw.nodes ?? [];
  } catch {
    return [];
  }
}

function loadEdges(): TransitGraphEdge[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const raw = require("./transitGraph.edges.json") as { edges: TransitGraphEdge[] };
    return raw.edges ?? [];
  } catch {
    return [];
  }
}

export const TRANSIT_GRAPH_NODES: TransitGraphNode[] = loadNodes();
export const TRANSIT_GRAPH_EDGES: TransitGraphEdge[] = loadEdges();

function km(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLng = ((bLng - aLng) * Math.PI) / 180;
  const la1 = (aLat * Math.PI) / 180;
  const la2 = (bLat * Math.PI) / 180;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(la1) * Math.cos(la2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** Nearest N transit graph nodes to a point, sorted by distance. */
export function nearestGraphStations(
  lat: number,
  lng: number,
  n: number = 5
): (TransitGraphNode & { km: number })[] {
  return TRANSIT_GRAPH_NODES
    .map((s) => ({ ...s, km: km(lat, lng, s.lat, s.lng) }))
    .sort((a, b) => a.km - b.km)
    .slice(0, n);
}

/** Convert a TransitGraphNode to the legacy RailStation shape for compatibility. */
export function toRailStation(node: TransitGraphNode): RailStation & { km?: number } {
  return {
    th: node.nameTh || node.nameEn,
    en: node.nameEn || node.nameTh,
    lat: node.lat,
    lng: node.lng,
    system: node.system,
  };
}
