// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Regenerate after seeding: `node scripts/gen-registry.mjs`.
// Metadata (below) is tiny and statically imported for the picker; each district's
// full POI list loads lazily via DISTRICT_LOADERS so the bundle stays small.
import type { SeedDistrict } from "@/lib/plan/buildPlan";

export type DistrictTier = "neighborhood" | "district";
export interface DistrictMeta {
  key: string;
  th: string;
  en: string;
  tier: DistrictTier;
  zone: string;
  count: number;
  lat: number;
  lng: number;
}

export const DISTRICTS: DistrictMeta[] = [
  { key: "ekkamai", th: "เอกมัย", en: "ekkamai", tier: "neighborhood", zone: "ย่านยอดนิยม", count: 187, lat: 13.72705, lng: 100.58494 },
  { key: "thonglor", th: "ทองหล่อ", en: "thonglor", tier: "neighborhood", zone: "ย่านยอดนิยม", count: 176, lat: 13.73177, lng: 100.57895 },
  { key: "siam", th: "สยาม", en: "siam", tier: "neighborhood", zone: "ย่านยอดนิยม", count: 150, lat: 13.74717, lng: 100.53351 },
  { key: "silom", th: "สีลม", en: "silom", tier: "neighborhood", zone: "ย่านยอดนิยม", count: 146, lat: 13.72636, lng: 100.53154 },
  { key: "ari", th: "อารีย์", en: "ari", tier: "neighborhood", zone: "ย่านยอดนิยม", count: 106, lat: 13.78244, lng: 100.54392 },
  { key: "vadhana", th: "วัฒนา", en: "Vadhana", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 331, lat: 13.73308, lng: 100.57362 },
  { key: "khlong-toei", th: "คลองเตย", en: "Khlong Toei", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 283, lat: 13.72742, lng: 100.56754 },
  { key: "phra-nakhon", th: "พระนคร", en: "Phra Nakhon", tier: "district", zone: "กรุงเทพชั้นใน", count: 248, lat: 13.75846, lng: 100.49754 },
  { key: "bang-rak", th: "บางรัก", en: "Bang Rak", tier: "district", zone: "กรุงเทพชั้นใน", count: 238, lat: 13.72649, lng: 100.52665 },
  { key: "pathum-wan", th: "ปทุมวัน", en: "Pathum Wan", tier: "district", zone: "กรุงเทพชั้นใน", count: 236, lat: 13.74299, lng: 100.53637 },
  { key: "chatuchak", th: "จตุจักร", en: "Chatuchak", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 232, lat: 13.82781, lng: 100.56676 },
  { key: "samphanthawong", th: "สัมพันธวงศ์", en: "Samphanthawong", tier: "district", zone: "กรุงเทพชั้นใน", count: 227, lat: 13.73764, lng: 100.51101 },
  { key: "ratchathewi", th: "ราชเทวี", en: "Ratchathewi", tier: "district", zone: "กรุงเทพชั้นใน", count: 211, lat: 13.75752, lng: 100.53617 },
  { key: "lat-krabang", th: "ลาดกระบัง", en: "Lat Krabang", tier: "district", zone: "กรุงเทพตะวันออก", count: 205, lat: 13.72871, lng: 100.7691 },
  { key: "sathon", th: "สาทร", en: "Sathon", tier: "district", zone: "กรุงเทพชั้นใน", count: 185, lat: 13.7182, lng: 100.53598 },
  { key: "din-daeng", th: "ดินแดง", en: "Din Daeng", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 170, lat: 13.77384, lng: 100.56395 },
  { key: "phaya-thai", th: "พญาไท", en: "Phaya Thai", tier: "district", zone: "กรุงเทพชั้นใน", count: 154, lat: 13.78224, lng: 100.54297 },
  { key: "yan-nawa", th: "ยานนาวา", en: "Yan Nawa", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 151, lat: 13.69757, lng: 100.54003 },
  { key: "bang-khun-thian", th: "บางขุนเทียน", en: "Bang Khun Thian", tier: "district", zone: "ฝั่งธนบุรี", count: 142, lat: 13.59748, lng: 100.42928 },
  { key: "prawet", th: "ประเวศ", en: "Prawet", tier: "district", zone: "กรุงเทพตะวันออก", count: 136, lat: 13.69965, lng: 100.6707 },
  { key: "phasi-charoen", th: "ภาษีเจริญ", en: "Phasi Charoen", tier: "district", zone: "ฝั่งธนบุรี", count: 122, lat: 13.72285, lng: 100.44921 },
  { key: "taling-chan", th: "ตลิ่งชัน", en: "Taling Chan", tier: "district", zone: "ฝั่งธนบุรี", count: 122, lat: 13.76584, lng: 100.4409 },
  { key: "dusit", th: "ดุสิต", en: "Dusit", tier: "district", zone: "กรุงเทพชั้นใน", count: 119, lat: 13.7766, lng: 100.51283 },
  { key: "huai-khwang", th: "ห้วยขวาง", en: "Huai Khwang", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 118, lat: 13.77001, lng: 100.57772 },
  { key: "bang-khen", th: "บางเขน", en: "Bang Khen", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 116, lat: 13.85902, lng: 100.6363 },
  { key: "pom-prap-sattru-phai", th: "ป้อมปราบศัตรูพ่าย", en: "Pom Prap Sattru Phai", tier: "district", zone: "กรุงเทพชั้นใน", count: 114, lat: 13.74778, lng: 100.51117 },
  { key: "bang-kapi", th: "บางกะปิ", en: "Bang Kapi", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 112, lat: 13.76579, lng: 100.63477 },
  { key: "bang-kho-laem", th: "บางคอแหลม", en: "Bang Kho Laem", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 101, lat: 13.70155, lng: 100.51033 },
  { key: "bueng-kum", th: "บึงกุ่ม", en: "Bueng Kum", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 99, lat: 13.80787, lng: 100.65442 },
  { key: "bang-phlat", th: "บางพลัด", en: "Bang Phlat", tier: "district", zone: "ฝั่งธนบุรี", count: 97, lat: 13.78469, lng: 100.4891 },
  { key: "khlong-san", th: "คลองสาน", en: "Khlong San", tier: "district", zone: "ฝั่งธนบุรี", count: 97, lat: 13.72495, lng: 100.50419 },
  { key: "khan-na-yao", th: "คันนายาว", en: "Khan Na Yao", tier: "district", zone: "กรุงเทพตะวันออก", count: 96, lat: 13.8261, lng: 100.67034 },
  { key: "lat-phrao", th: "ลาดพร้าว", en: "Lat Phrao", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 96, lat: 13.82724, lng: 100.60644 },
  { key: "bang-na", th: "บางนา", en: "Bang Na", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 87, lat: 13.66649, lng: 100.62441 },
  { key: "bangkok-noi", th: "บางกอกน้อย", en: "Bangkok Noi", tier: "district", zone: "ฝั่งธนบุรี", count: 86, lat: 13.75976, lng: 100.4783 },
  { key: "suan-luang", th: "สวนหลวง", en: "Suan Luang", tier: "district", zone: "กรุงเทพตะวันออก", count: 82, lat: 13.72972, lng: 100.6283 },
  { key: "thon-buri", th: "ธนบุรี", en: "Thon Buri", tier: "district", zone: "ฝั่งธนบุรี", count: 79, lat: 13.71803, lng: 100.4867 },
  { key: "bang-khae", th: "บางแค", en: "Bang Khae", tier: "district", zone: "ฝั่งธนบุรี", count: 71, lat: 13.71175, lng: 100.39466 },
  { key: "don-mueang", th: "ดอนเมือง", en: "Don Mueang", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 70, lat: 13.92305, lng: 100.5925 },
  { key: "chom-thong", th: "จอมทอง", en: "Chom Thong", tier: "district", zone: "ฝั่งธนบุรี", count: 69, lat: 13.68677, lng: 100.45967 },
  { key: "thung-khru", th: "ทุ่งครุ", en: "Thung Khru", tier: "district", zone: "ฝั่งธนบุรี", count: 67, lat: 13.64429, lng: 100.4949 },
  { key: "khlong-sam-wa", th: "คลองสามวา", en: "Khlong Sam Wa", tier: "district", zone: "กรุงเทพตะวันออก", count: 65, lat: 13.86645, lng: 100.71437 },
  { key: "sai-mai", th: "สายไหม", en: "Sai Mai", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 58, lat: 13.91179, lng: 100.65798 },
  { key: "bang-bon", th: "บางบอน", en: "Bang Bon", tier: "district", zone: "ฝั่งธนบุรี", count: 55, lat: 13.66182, lng: 100.40671 },
  { key: "wang-thonglang", th: "วังทองหลาง", en: "Wang Thonglang", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 55, lat: 13.77918, lng: 100.60981 },
  { key: "bang-sue", th: "บางซื่อ", en: "Bang Sue", tier: "district", zone: "กรุงเทพชั้นใน", count: 48, lat: 13.82003, lng: 100.52577 },
  { key: "lak-si", th: "หลักสี่", en: "Lak Si", tier: "district", zone: "รัชดา–ลาดพร้าว–เหนือ", count: 48, lat: 13.87732, lng: 100.56141 },
  { key: "bangkok-yai", th: "บางกอกใหญ่", en: "Bangkok Yai", tier: "district", zone: "ฝั่งธนบุรี", count: 43, lat: 13.73882, lng: 100.48187 },
  { key: "nong-chok", th: "หนองจอก", en: "Nong Chok", tier: "district", zone: "กรุงเทพตะวันออก", count: 41, lat: 13.85385, lng: 100.84996 },
  { key: "phra-khanong", th: "พระโขนง", en: "Phra Khanong", tier: "district", zone: "สุขุมวิท–ฝั่งใต้", count: 34, lat: 13.6913, lng: 100.61347 },
  { key: "saphan-sung", th: "สะพานสูง", en: "Saphan Sung", tier: "district", zone: "กรุงเทพตะวันออก", count: 34, lat: 13.76537, lng: 100.68409 },
  { key: "thawi-watthana", th: "ทวีวัฒนา", en: "Thawi Watthana", tier: "district", zone: "ฝั่งธนบุรี", count: 33, lat: 13.77763, lng: 100.37441 },
  { key: "min-buri", th: "มีนบุรี", en: "Min Buri", tier: "district", zone: "กรุงเทพตะวันออก", count: 31, lat: 13.81202, lng: 100.73358 },
  { key: "nong-khaem", th: "หนองแขม", en: "Nong Khaem", tier: "district", zone: "ฝั่งธนบุรี", count: 27, lat: 13.69647, lng: 100.35079 },
  { key: "rat-burana", th: "ราษฎร์บูรณะ", en: "Rat Burana", tier: "district", zone: "ฝั่งธนบุรี", count: 19, lat: 13.67605, lng: 100.50157 },
];

export const DISTRICT_KEYS: string[] = DISTRICTS.map((d) => d.key);

export const DISTRICT_LOADERS: Record<string, () => Promise<SeedDistrict>> = {
  "ekkamai": () => import("@/data/seed/ekkamai.json").then((mod) => mod.default as unknown as SeedDistrict),
  "thonglor": () => import("@/data/seed/thonglor.json").then((mod) => mod.default as unknown as SeedDistrict),
  "siam": () => import("@/data/seed/siam.json").then((mod) => mod.default as unknown as SeedDistrict),
  "silom": () => import("@/data/seed/silom.json").then((mod) => mod.default as unknown as SeedDistrict),
  "ari": () => import("@/data/seed/ari.json").then((mod) => mod.default as unknown as SeedDistrict),
  "vadhana": () => import("@/data/seed/vadhana.json").then((mod) => mod.default as unknown as SeedDistrict),
  "khlong-toei": () => import("@/data/seed/khlong-toei.json").then((mod) => mod.default as unknown as SeedDistrict),
  "phra-nakhon": () => import("@/data/seed/phra-nakhon.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-rak": () => import("@/data/seed/bang-rak.json").then((mod) => mod.default as unknown as SeedDistrict),
  "pathum-wan": () => import("@/data/seed/pathum-wan.json").then((mod) => mod.default as unknown as SeedDistrict),
  "chatuchak": () => import("@/data/seed/chatuchak.json").then((mod) => mod.default as unknown as SeedDistrict),
  "samphanthawong": () => import("@/data/seed/samphanthawong.json").then((mod) => mod.default as unknown as SeedDistrict),
  "ratchathewi": () => import("@/data/seed/ratchathewi.json").then((mod) => mod.default as unknown as SeedDistrict),
  "lat-krabang": () => import("@/data/seed/lat-krabang.json").then((mod) => mod.default as unknown as SeedDistrict),
  "sathon": () => import("@/data/seed/sathon.json").then((mod) => mod.default as unknown as SeedDistrict),
  "din-daeng": () => import("@/data/seed/din-daeng.json").then((mod) => mod.default as unknown as SeedDistrict),
  "phaya-thai": () => import("@/data/seed/phaya-thai.json").then((mod) => mod.default as unknown as SeedDistrict),
  "yan-nawa": () => import("@/data/seed/yan-nawa.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-khun-thian": () => import("@/data/seed/bang-khun-thian.json").then((mod) => mod.default as unknown as SeedDistrict),
  "prawet": () => import("@/data/seed/prawet.json").then((mod) => mod.default as unknown as SeedDistrict),
  "phasi-charoen": () => import("@/data/seed/phasi-charoen.json").then((mod) => mod.default as unknown as SeedDistrict),
  "taling-chan": () => import("@/data/seed/taling-chan.json").then((mod) => mod.default as unknown as SeedDistrict),
  "dusit": () => import("@/data/seed/dusit.json").then((mod) => mod.default as unknown as SeedDistrict),
  "huai-khwang": () => import("@/data/seed/huai-khwang.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-khen": () => import("@/data/seed/bang-khen.json").then((mod) => mod.default as unknown as SeedDistrict),
  "pom-prap-sattru-phai": () => import("@/data/seed/pom-prap-sattru-phai.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-kapi": () => import("@/data/seed/bang-kapi.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-kho-laem": () => import("@/data/seed/bang-kho-laem.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bueng-kum": () => import("@/data/seed/bueng-kum.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-phlat": () => import("@/data/seed/bang-phlat.json").then((mod) => mod.default as unknown as SeedDistrict),
  "khlong-san": () => import("@/data/seed/khlong-san.json").then((mod) => mod.default as unknown as SeedDistrict),
  "khan-na-yao": () => import("@/data/seed/khan-na-yao.json").then((mod) => mod.default as unknown as SeedDistrict),
  "lat-phrao": () => import("@/data/seed/lat-phrao.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-na": () => import("@/data/seed/bang-na.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bangkok-noi": () => import("@/data/seed/bangkok-noi.json").then((mod) => mod.default as unknown as SeedDistrict),
  "suan-luang": () => import("@/data/seed/suan-luang.json").then((mod) => mod.default as unknown as SeedDistrict),
  "thon-buri": () => import("@/data/seed/thon-buri.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-khae": () => import("@/data/seed/bang-khae.json").then((mod) => mod.default as unknown as SeedDistrict),
  "don-mueang": () => import("@/data/seed/don-mueang.json").then((mod) => mod.default as unknown as SeedDistrict),
  "chom-thong": () => import("@/data/seed/chom-thong.json").then((mod) => mod.default as unknown as SeedDistrict),
  "thung-khru": () => import("@/data/seed/thung-khru.json").then((mod) => mod.default as unknown as SeedDistrict),
  "khlong-sam-wa": () => import("@/data/seed/khlong-sam-wa.json").then((mod) => mod.default as unknown as SeedDistrict),
  "sai-mai": () => import("@/data/seed/sai-mai.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-bon": () => import("@/data/seed/bang-bon.json").then((mod) => mod.default as unknown as SeedDistrict),
  "wang-thonglang": () => import("@/data/seed/wang-thonglang.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bang-sue": () => import("@/data/seed/bang-sue.json").then((mod) => mod.default as unknown as SeedDistrict),
  "lak-si": () => import("@/data/seed/lak-si.json").then((mod) => mod.default as unknown as SeedDistrict),
  "bangkok-yai": () => import("@/data/seed/bangkok-yai.json").then((mod) => mod.default as unknown as SeedDistrict),
  "nong-chok": () => import("@/data/seed/nong-chok.json").then((mod) => mod.default as unknown as SeedDistrict),
  "phra-khanong": () => import("@/data/seed/phra-khanong.json").then((mod) => mod.default as unknown as SeedDistrict),
  "saphan-sung": () => import("@/data/seed/saphan-sung.json").then((mod) => mod.default as unknown as SeedDistrict),
  "thawi-watthana": () => import("@/data/seed/thawi-watthana.json").then((mod) => mod.default as unknown as SeedDistrict),
  "min-buri": () => import("@/data/seed/min-buri.json").then((mod) => mod.default as unknown as SeedDistrict),
  "nong-khaem": () => import("@/data/seed/nong-khaem.json").then((mod) => mod.default as unknown as SeedDistrict),
  "rat-burana": () => import("@/data/seed/rat-burana.json").then((mod) => mod.default as unknown as SeedDistrict),
};

// Picker grouping order (neighbourhoods first, then by rough geography).
export const ZONE_ORDER: string[] = [
  "ย่านยอดนิยม",
  "กรุงเทพชั้นใน",
  "สุขุมวิท–ฝั่งใต้",
  "รัชดา–ลาดพร้าว–เหนือ",
  "ฝั่งธนบุรี",
  "กรุงเทพตะวันออก",
  "พื้นที่อื่น",
];
