-- arnfa_0005_shared_links.sql
-- Create a table for short links generated by the share button.
-- Anyone can create a short link, and anyone can read it.
-- The ID will be a randomly generated short string.

create table if not exists arnfa.shared_link (
  id text primary key,
  state_qs text not null,
  created_at timestamptz not null default now()
);

-- RLS
alter table arnfa.shared_link enable row level security;

-- Public read access
create policy shared_link_public_read on arnfa.shared_link for select using (true);

-- Public insert access (no authentication required)
create policy shared_link_public_insert on arnfa.shared_link for insert with check (true);

-- Grants
grant select, insert on arnfa.shared_link to anon, authenticated;
